# Generated by Django 4.2.5 on 2023-12-12 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('membership_types', models.CharField(choices=[('basic', 'Basic'), ('gold', 'Gold')], default='basic', max_length=20)),
                ('billing_address', models.CharField(choices=[('online', 'Online'), ('case', 'Case')], max_length=20)),
                ('date_of_signature', models.DateTimeField(default=django.utils.timezone.now)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('service_category', models.ManyToManyField(to='cms_app.service_category')),
                ('sub_category', models.ManyToManyField(to='cms_app.sub_category')),
            ],
        ),
    ]
