# Generated by Django 4.2.5 on 2023-12-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_plan_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms_app.displayprofile')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms_app.plan_subscription')),
            ],
        ),
    ]
