# Generated by Django 4.2.5 on 2023-12-12 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_subscription',
            name='message',
            field=models.CharField(default=datetime.datetime(2023, 12, 12, 10, 53, 7, 586459, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan_subscription',
            name='price',
            field=models.IntegerField(),
        ),
    ]
