# Generated by Django 4.2.5 on 2023-12-13 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_attendance_attendance_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
