# Generated by Django 4.2.5 on 2023-12-13 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0010_inventory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybalance',
            name='images',
            field=models.ImageField(default=datetime.datetime(2023, 12, 13, 10, 23, 8, 339089, tzinfo=datetime.timezone.utc), upload_to='Inventory_balance/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
