# Generated by Django 4.2.5 on 2023-12-14 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0011_inventorybalance_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmember',
            name='images',
            field=models.ImageField(default=datetime.datetime(2023, 12, 14, 6, 56, 39, 749104, tzinfo=datetime.timezone.utc), upload_to='Addmember/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
