# Generated by Django 4.2.5 on 2023-12-14 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0012_addmember_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='images',
            field=models.ImageField(default=datetime.datetime(2023, 12, 14, 7, 14, 15, 192230, tzinfo=datetime.timezone.utc), upload_to='Attendance/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
