# Generated by Django 4.2.5 on 2023-12-17 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0016_alter_addmember_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.addmember'),
        ),
    ]
