# Generated by Django 4.2.5 on 2023-12-17 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0017_alter_cashtransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.addmember'),
        ),
    ]
