# Generated by Django 4.2.5 on 2023-12-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0018_alter_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybalance',
            name='inventory',
            field=models.CharField(max_length=100),
        ),
    ]
